### ISSUE TITLE
Aufnahme von Tibber als Stromlieferant analog awattar

### ISSUE THREAD

**Issue by svenp** [Maverick78de/SMA_forecast_charging#2]
Hallo,

Es wäre schön, wenn in Zukunft auch der Stromlieferant Tibber (evtl. werden weitere folgen) zusätzlich zum awattar aufgenommen werden könnte.

Eine Abfrage des Preises erfolgt via persönlichem token.
Hier ein Beispiel mit dem Demo Token für das get_awattar script

> var addprice = 19.76;
const token = "Bearer d1007ead2dc84a2b82f0de19451c5fb22112f7ae11d19bf2bedb224a003ff74a";
function requestData() {
var options = {
  uri: 'https://api.tibber.com/v1-beta/gql',
  method: 'POST',
  body: '{"query": "{viewer {homes {currentSubscription {priceInfo {current {total energy level tax startsAt }today {total energy level tax startsAt }tomorrow {total energy level tax startsAt }}}}}}" }',
    headers: {
    'Authorization': token,
    'Content-Type': 'application/json'
 }
};
    request(options, (error, response, body) => {
   

Als Ergebnis bekommt man dann das json:
` {"data":{"viewer":{"homes":[{"currentSubscription":{"priceInfo":{"current":{"total":0.1812,"energy":0.1254,"level":"VERY_CHEAP","tax":0.0558,"startsAt":"2020-06-19T09:00:00+02:00"},"today":[{"total":0.0896,"energy":0.0522,"level":"VERY_CHEAP","tax":0.0374,"startsAt":"2020-06-19T00:00:00+02:00"},{"total":0.0821,"energy":0.0462,"level":"VERY_CHEAP","tax":0.0359,"startsAt":"2020-06-19T01:00:00+02:00"},{"total":0.0663,"energy":0.0335,"level":"VERY_CHEAP","tax":0.0328,"startsAt":"2020-06-19T02:00:00+02:00"},{"total":0.0511,"energy":0.0214,"level":"VERY_CHEAP","tax":0.0297,"startsAt":"2020-06-19T03:00:00+02:00"},{"total":0.0467,"energy":0.0179,"level":"VERY_CHEAP","tax":0.0288,"startsAt":"2020-06-19T04:00:00+02:00"},{"total":0.0789,"energy":0.0436,"level":"VERY_CHEAP","tax":0.0353,"startsAt":"2020-06-19T05:00:00+02:00"},{"total":0.0992,"energy":0.0598,"level":"VERY_CHEAP","tax":0.0394,"startsAt":"2020-06-19T06:00:00+02:00"},{"total":0.1713,"energy":0.1176,"level":"VERY_CHEAP","tax":0.0537,"startsAt":"2020-06-19T07:00:00+02:00"},{"total":0.1746,"energy":0.1202,"level":"VERY_CHEAP","tax":0.0544,"startsAt":"2020-06-19T08:00:00+02:00"},{"total":0.1812,"energy":0.1254,"level":"VERY_CHEAP","tax":0.0558,"startsAt":"2020-06-19T09:00:00+02:00"},{"total":0.184,"energy":0.1277,"level":"VERY_CHEAP","tax":0.0563,"startsAt":"2020-06-19T10:00:00+02:00"},{"total":0.1838,"energy":0.1276,"level":"VERY_CHEAP","tax":0.0562,"startsAt":"2020-06-19T11:00:00+02:00"},{"total":0.179,"energy":0.1237,"level":"VERY_CHEAP","tax":0.0553,"startsAt":"2020-06-19T12:00:00+02:00"},{"total":0.172,"energy":0.1181,"level":"VERY_CHEAP","tax":0.0539,"startsAt":"2020-06-19T13:00:00+02:00"},{"total":0.142,"energy":0.0941,"level":"VERY_CHEAP","tax":0.0479,"startsAt":"2020-06-19T14:00:00+02:00"},{"total":0.1419,"energy":0.094,"level":"VERY_CHEAP","tax":0.0479,"startsAt":"2020-06-19T15:00:00+02:00"},{"total":0.1698,"energy":0.1163,"level":"VERY_CHEAP","tax":0.0535,"startsAt":"2020-06-19T16:00:00+02:00"},{"total":0.1707,"energy":0.117,"level":"VERY_CHEAP","tax":0.0537,"startsAt":"2020-06-19T17:00:00+02:00"},{"total":0.1575,"energy":0.1065,"level":"VERY_CHEAP","tax":0.051,"startsAt":"2020-06-19T18:00:00+02:00"},{"total":0.1415,"energy":0.0937,"level":"VERY_CHEAP","tax":0.0478,"startsAt":"2020-06-19T19:00:00+02:00"},{"total":0.1042,"energy":0.0638,"level":"VERY_CHEAP","tax":0.0404,"startsAt":"2020-06-19T20:00:00+02:00"},{"total":0.0992,"energy":0.0598,"level":"VERY_CHEAP","tax":0.0394,"startsAt":"2020-06-19T21:00:00+02:00"},{"total":0.0894,"energy":0.052,"level":"VERY_CHEAP","tax":0.0374,"startsAt":"2020-06-19T22:00:00+02:00"},{"total":0.071,"energy":0.0373,"level":"VERY_CHEAP","tax":0.0337,"startsAt":"2020-06-19T23:00:00+02:00"}],"tomorrow":[]}}}]}}}
`

Tomorrow wird analog ausgeführt sobald die Börsendaten ab 13-14Uhr vefrügbar sind. mit dem Datum von morgen.
total = Strompreis (energy + tax)
Durch Anpassung der Abfrage kann man auch z.B zusätlzich den aktuellen Preis abfragen

API : [hier](https://developer.tibber.com/docs/overview)

**Comment by Maverick78de** [comment]
Ich habe mich daran gerade mal versucht, aus zeitlichen Gründen kann ich da im Moment nicht tiefer einsteigen. Ich bekomme als Currency NOK und nicht EUR raus und irgendwas passt da nicht. Habe es auch nicht hinbekommen das auf DE als Adressvorgabe einzuschränken.
Ich brauche eine Query die mir folgenden Output liefert, irgendeine Art Preis für des nächsten 24h ab **JETZT**. Mit Angaben wie Morgen und Heute usw macht das ganze nicht wirklich einfach in der Umsetzung. Aus zeitlichen Gründen brauch ich hier zuarbeit.

**Comment by svenp** [comment]
Habe auch mal versucht die Abfrage anzupasen.

` body: '{"query": "{viewer {homes {currentSubscription {priceInfo {range(resolution: HOURLY, first:48 )  { nodes {total energy level tax startsAt }}}}}}}" }',`

Damit kommen alle Daten von heute 0Uhr bis morgen 24Uhr
Das kann man ja per counter im Array auf die aktuelle Stunde eingrenzen.
Leider kann ich derzeit auch nur die Demo Daten abrufen, und die sind deshalb in Kronen. 
Sobald mein "personal Token" funktioniert werde ich der Sache weiter nachgehen und mich hier melden

**Comment by Maverick78de** [comment]
Sollte so funktionieren. Ohne validen token kann ich nicht mehr dazu sagen.

`const url = 'https://api.tibber.com/v1-beta/gql'
var addprice = 18.52 /* Regionaler aufpreis*/
const token = "Bearer d1007ead2dc84a2b82f0de19451c5fb22112f7ae11d19bf2bedb224a003ff74a"

function requestData() {
 
    const options = {
        uri: url,
        method: 'POST',
        body: '{"query": "{viewer {homes {currentSubscription {priceInfo {range(resolution: HOURLY, first:48 ) { nodes {total startsAt }}}}}}}" }',
        headers: {
            'Authorization': token,
        'Content-Type': 'application/json'
        }
    }
 
    request(options, (error, response, body) => {
        
        if(error) return console.log(error);
 
        if(response.statusCode == 200) {
            let array = JSON.parse(body).data.viewer.homes[0].currentSubscription.priceInfo.range.nodes
            let jetzt = new Date();
            for(let i = jetzt.getHours(); i < array.length; i++) {

                let stateBaseName = "electricity.prices." + i + ".";
                
                createState(stateBaseName + "startTime", "", {
                    read: true,
                    write: true,
                    name: "Gultigkeitsbeginn (Uhrzeit)",
                    type: "string",
                    def: false
                });
 
                createState(stateBaseName + "startDate", "", {
                    read: true,
                    write: true,
                    name: "Gultigkeitsbeginn (Datum)",
                    type: "string",
                    def: false
                });
 
                createState(stateBaseName + "endTime", "", {
                    read: true,
                    write: true,
                    name: "Gultigkeitsende (Uhrzeit)",
                    type: "string",
                    def: false
                });
 
                createState(stateBaseName + "price", 0, {
                    read: true,
                    write: true,
                    name: "Preis",
                    type: "number",
                    def: 0
                });
 
                let start = new Date(array[i].startsAt);
                var options = { hour12: false, hour: '2-digit', minute:'2-digit'};
                let startTime = start.toLocaleTimeString('de-DE', options);
                let startDate = start.toLocaleDateString('de-DE');
                 
                let end = new Date(array[i].startsAt).getTime()+3600000
                let endTime = new Date(end).toLocaleTimeString('de-DE', options);
 
                let mwhprice = array[i].total;
                let price = Number(mwhprice) + addprice;
                //console.log(startTime + ',' + startDate + ',' + startTime + ',' + endTime + ',' + price )
                
                setState(stateBaseName + "startTime", startTime);
                setState(stateBaseName + "startDate", startDate);
                setState(stateBaseName + "endTime", endTime);
                setState(stateBaseName + "price", price);
            };
            array.sort(function (a, b) {
                return a.marketprice - b.marketprice
            });
            var batprice = getState("javascript.0.electricity.prices.batprice").val;
            var minprice = array[0].marketprice + addprice;
            if ( minprice > batprice ) {
                minprice = batprice;
            }
            var maxprice = array[array.length - 1].marketprice + addprice;
            var diffprice = maxprice - minprice;
            var redprice = maxprice - (diffprice/2);
            if ( redprice < batprice ) {
                redprice = batprice;
            }
            setState("javascript.0.electricity.prices.redprice", redprice); 
        };
    });
}
requestData();
schedule("0 * * * *", function () {
    requestData();
});
`

**Comment by svenp** [comment]
Schaut erstmal ganz gut aus soweit. 
Danke für das schnelle einbinden der Tibber Abfrage. 
Laut Aussage von Tibber, sollen die Preise in den nächsten 14 Tagen verfügbar sein, dann wissen wir mehr.

**Comment by Maverick78de** [comment]
Gibt es hier noch etwas zu tuen?

**Comment by svenp** [comment]
Aufgrund des hohen Ansturms auf Tibber sind Sie wohl etwas in Verzug geraten. 
Meine Umstellung erfolgt am 30.07. Aktuell kann ich noch keine Preise abrufen.
Warten wir noch etwas ab, ggf muss ich dann nochmal bei Tibber nachharken.

**Comment by svenp** [comment]
So jetzt funktioniert scheinbar auch das abrufen der Presidaten bei Tibber.

Die Daten kommen wie folgt an:
{"data":{"viewer":{"homes":[{"currentSubscription":{"priceInfo":{"current":{"total":0.2336,"energy":0.0351,"level":"NORMAL","tax":0.1985,"startsAt":"2020-09-25T16:00:00+02:00"},"today":[{"total":0.2316,"energy":0.0333,"level":"NORMAL","tax":0.1983,"startsAt":"2020-09-25T00:00:00+02:00"},{"total":0.2299,"energy":0.0319,"level":"NORMAL","tax":0.198,"startsAt":"2020-09-25T01:00:00+02:00"},{"total":0.2266,"energy":0.029,"level":"NORMAL","tax":0.1976,"startsAt":"2020-09-25T02:00:00+02:00"},{"total":0.2245,"energy":0.0272,"level":"NORMAL","tax":0.1973,"startsAt":"2020-09-25T03:00:00+02:00"},{"total":0.2257,"energy":0.0283,"level":"NORMAL","tax":0.1974,"startsAt":"2020-09-25T04:00:00+02:00"},{"total":0.2278,"energy":0.0301,"level":"NORMAL","tax":0.1977,"startsAt":"2020-09-25T05:00:00+02:00"},{"total":0.2413,"energy":0.0417,"level":"NORMAL","tax":0.1996,"startsAt":"2020-09-25T06:00:00+02:00"},{"total":0.2531,"energy":0.0519,"level":"NORMAL","tax":0.2012,"startsAt":"2020-09-25T07:00:00+02:00"},{"total":0.2584,"energy":0.0565,"level":"NORMAL","tax":0.2019,"startsAt":"2020-09-25T08:00:00+02:00"},{"total":0.2543,"energy":0.053,"level":"NORMAL","tax":0.2013,"startsAt":"2020-09-25T09:00:00+02:00"},{"total":0.2488,"energy":0.0482,"level":"NORMAL","tax":0.2006,"startsAt":"2020-09-25T10:00:00+02:00"},{"total":0.2477,"energy":0.0473,"level":"NORMAL","tax":0.2004,"startsAt":"2020-09-25T11:00:00+02:00"},{"total":0.2465,"energy":0.0462,"level":"NORMAL","tax":0.2003,"startsAt":"2020-09-25T12:00:00+02:00"},{"total":0.2405,"energy":0.0411,"level":"NORMAL","tax":0.1994,"startsAt":"2020-09-25T13:00:00+02:00"},{"total":0.2344,"energy":0.0358,"level":"NORMAL","tax":0.1986,"startsAt":"2020-09-25T14:00:00+02:00"},{"total":0.2328,"energy":0.0344,"level":"NORMAL","tax":0.1984,"startsAt":"2020-09-25T15:00:00+02:00"},{"total":0.2336,"energy":0.0351,"level":"NORMAL","tax":0.1985,"startsAt":"2020-09-25T16:00:00+02:00"},{"total":0.2459,"energy":0.0457,"level":"NORMAL","tax":0.2002,"startsAt":"2020-09-25T17:00:00+02:00"},{"total":0.252,"energy":0.0509,"level":"NORMAL","tax":0.2011,"startsAt":"2020-09-25T18:00:00+02:00"},{"total":0.2545,"energy":0.0531,"level":"NORMAL","tax":0.2014,"startsAt":"2020-09-25T19:00:00+02:00"},{"total":0.2523,"energy":0.0512,"level":"NORMAL","tax":0.2011,"startsAt":"2020-09-25T20:00:00+02:00"},{"total":0.2463,"energy":0.046,"level":"NORMAL","tax":0.2003,"startsAt":"2020-09-25T21:00:00+02:00"},{"total":0.2391,"energy":0.0398,"level":"NORMAL","tax":0.1993,"startsAt":"2020-09-25T22:00:00+02:00"},{"total":0.2336,"energy":0.0351,"level":"NORMAL","tax":0.1985,"startsAt":"2020-09-25T23:00:00+02:00"}],"tomorrow":[{"total":0.2324,"energy":0.034,"level":"NORMAL","tax":0.1984,"startsAt":"2020-09-26T00:00:00+02:00"},{"total":0.2285,"energy":0.0307,"level":"NORMAL","tax":0.1978,"startsAt":"2020-09-26T01:00:00+02:00"},{"total":0.2254,"energy":0.028,"level":"NORMAL","tax":0.1974,"startsAt":"2020-09-26T02:00:00+02:00"},{"total":0.2235,"energy":0.0264,"level":"NORMAL","tax":0.1971,"startsAt":"2020-09-26T03:00:00+02:00"},{"total":0.223,"energy":0.0259,"level":"NORMAL","tax":0.1971,"startsAt":"2020-09-26T04:00:00+02:00"},{"total":0.2244,"energy":0.0272,"level":"NORMAL","tax":0.1972,"startsAt":"2020-09-26T05:00:00+02:00"},{"total":0.2265,"energy":0.029,"level":"NORMAL","tax":0.1975,"startsAt":"2020-09-26T06:00:00+02:00"},{"total":0.23,"energy":0.032,"level":"NORMAL","tax":0.198,"startsAt":"2020-09-26T07:00:00+02:00"},{"total":0.2355,"energy":0.0367,"level":"NORMAL","tax":0.1988,"startsAt":"2020-09-26T08:00:00+02:00"},{"total":0.2407,"energy":0.0412,"level":"NORMAL","tax":0.1995,"startsAt":"2020-09-26T09:00:00+02:00"},{"total":0.2386,"energy":0.0394,"level":"NORMAL","tax":0.1992,"startsAt":"2020-09-26T10:00:00+02:00"},{"total":0.2371,"energy":0.0381,"level":"NORMAL","tax":0.199,"startsAt":"2020-09-26T11:00:00+02:00"},{"total":0.2324,"energy":0.0341,"level":"NORMAL","tax":0.1983,"startsAt":"2020-09-26T12:00:00+02:00"},{"total":0.2301,"energy":0.032,"level":"NORMAL","tax":0.1981,"startsAt":"2020-09-26T13:00:00+02:00"},{"total":0.2264,"energy":0.0289,"level":"NORMAL","tax":0.1975,"startsAt":"2020-09-26T14:00:00+02:00"},{"total":0.2253,"energy":0.0279,"level":"NORMAL","tax":0.1974,"startsAt":"2020-09-26T15:00:00+02:00"},{"total":0.2268,"energy":0.0292,"level":"NORMAL","tax":0.1976,"startsAt":"2020-09-26T16:00:00+02:00"},{"total":0.2323,"energy":0.034,"level":"NORMAL","tax":0.1983,"startsAt":"2020-09-26T17:00:00+02:00"},{"total":0.2387,"energy":0.0395,"level":"NORMAL","tax":0.1992,"startsAt":"2020-09-26T18:00:00+02:00"},{"total":0.2457,"energy":0.0455,"level":"NORMAL","tax":0.2002,"startsAt":"2020-09-26T19:00:00+02:00"},{"total":0.2408,"energy":0.0412,"level":"NORMAL","tax":0.1996,"startsAt":"2020-09-26T20:00:00+02:00"},{"total":0.2324,"energy":0.0341,"level":"NORMAL","tax":0.1983,"startsAt":"2020-09-26T21:00:00+02:00"},{"total":0.2297,"energy":0.0318,"level":"NORMAL","tax":0.1979,"startsAt":"2020-09-26T22:00:00+02:00"},{"total":0.2258,"energy":0.0283,"level":"NORMAL","tax":0.1975,"startsAt":"2020-09-26T23:00:00+02:00"}]}}}]}}}
--


Ich denke das total ist der komplette Preis in Euro also alle Nebenkosten für Netzentgelte MwSt und Zertifikat
Damit könnte man sich das umrechenen mit addprice  sparen. Da man mit seinem jeweiligen personlichen Token die Daten abruft, werden die schon personalisiert sein.
Kontrolle der Website von Tibber hat ergeben: Preisangabe für meine PLZ ergibt genau den total Preis in der jeweiligen Stunde

Es wäre super das script auf den total preis abzufragen
Danke 
Gruß
Sven

**Comment by Maverick78de** [comment]
https://raw.githubusercontent.com/Maverick78de/SMA_forecast_charging/master/get_tibber_data_beta.js 

Bitte mal versuchen. Sollte von der Theorie so passen.

**Comment by svenp** [comment]
Hier das Ergebnis:
![Tibber](https://user-images.githubusercontent.com/649690/94299757-64bcd500-ff68-11ea-8c00-13716b6f624c.png)

Mit der Zeit gibts noch ein Probelm.

Wenn ich das log aktiviere

get_tibber_data: 23:00,2020-7-31,23:00,00:00,0.2373

**Comment by svenp** [comment]
![grafik](https://user-images.githubusercontent.com/649690/94338815-7ac4a700-fff5-11ea-8e8a-305760f2dc15.png)
Heute siehts mit der Zeit besser aus, aber das Datum stimmt leider nicht.

**Comment by Maverick78de** [comment]
Hab was geändert, nun sollte es passen

**Comment by Maverick78de** [comment]
Geht es jetzt?

**Comment by svenp** [comment]
> Geht es jetzt?

Augescheinlich sieht das Format erstmal passend aus, nur die Preise /Datum von Tibber stimmen nicht. 

Das liegt aber wohl an Tibber, hab da mal nen Ticket aufgemacht, man prüft die Lage.....
Melde mich wenn ich was neues habe.

**Comment by svenp** [comment]
Neuigkeiten von Tibber, 
die Abfrage mit den 48h bezieht sich auf die ersten 48 Stunden des Vertrages. 
Das hab ich da wohl fehlinterpretiert. 

Also geht leider nur die today und tomorrow Abfrage zu nutzen und die Stunden entsprechend rauszufiltern.....

`{
  viewer {
    homes {
      currentSubscription{
        priceInfo{
          today{
            total
            energy
            tax
            startsAt
          }
          tomorrow{
            total
            energy
            tax
            startsAt
          }
        }
      }
    }
  }
}`



Gruß
Sven

**Comment by Maverick78de** [comment]
Ich brauche ein Output, die Abfrage geht mit dem Token von oben nicht

**Comment by svenp** [comment]
[Output_Json_today_tomorrow.txt](https://github.com/Maverick78de/SMA_forecast_charging/files/5333587/Output_Json_today_tomorrow.txt)

OK Soweit?

**Comment by Maverick78de** [comment]
Oh je, na da muss ich mal schauen ob ich das hin gebastelt bekomme.

**Comment by Maverick78de** [comment]
Sollte so gehen: https://raw.githubusercontent.com/Maverick78de/SMA_forecast_charging/master/get_tibber_data_beta.js

**Comment by Maverick78de** [comment]
Da war noch ein Fehler, sollte jetzt gehen.

**Comment by svenp** [comment]
Das ging aber schnell :-)

So ganz rund scheint es leider doch noch nicht zu sein....
![image](https://user-images.githubusercontent.com/649690/95440240-ff4de880-0958-11eb-8cea-e1d6c52ce599.png)

Das Vis (rot) ist bei Awattar war von links an gefüllt gewesen. und Die Daten für morgen scheinen noch nicht da zu sein...
![image](https://user-images.githubusercontent.com/649690/95440426-3a501c00-0959-11eb-8358-578e78e9dae4.png)

**Comment by Maverick78de** [comment]
Wenn keine Daten für morgen da sind, kann auch nichts aufgefüllt werden.

**Comment by Maverick78de** [comment]
ah jetzt hab ich den Fehler gesehen ...

**Comment by Maverick78de** [comment]
ok sollte so gehen: https://raw.githubusercontent.com/Maverick78de/SMA_forecast_charging/master/get_tibber_data_beta.js

**Comment by svenp** [comment]
![image](https://user-images.githubusercontent.com/649690/95445910-e3017a00-095f-11eb-8bbb-8b9dc9c0e250.png)
Würde sagen sieht erstmal sehr gut aus...
Werde es die nächsten Tage beobachten...
Danke dafür
Gruß
Sven

**Comment by Maverick78de** [comment]
Da war noch ein Fehler drin. Jetzt ist es fehlerfrei.

**Comment by svenp** [comment]
Kann es sein das "redprice" nirgens als Datenpunkt erzeugt wird?
Bekomme da nen Fehler im Log

**Comment by Maverick78de** [comment]
Ach sorry, das ist aus dem Awattar Script mit rein gekommen und ist nur für meine Visualisierung. Ich nehm es raus.

**Comment by Maverick78de** [comment]
Da ich nichts mehr gehört habe, gehe ich davon aus, das dieses Script arbeitet?

**Comment by svenp** [comment]
Moin, 
ja soweit konnte ich keine Fehler mehr finden. 
Funktioniert gut soweit 
Danke
Gruß
Sven
