### ISSUE TITLE
Register Tagesertrag STP 8.0 3AV

### ISSUE THREAD

**Issue by ba179** [Maverick78de/SMA_forecast_charging#3]
Hi,

bei meinem STP 8.0 3AV funktioniert das Modbus Register 30517 (Tagesertrag) nicht. Nach ein "bisschen" rumprobieren und verzweifeln bin ich dann letztendlich über den folgenden Beitrag gestolpert, in dem von SMA die Aussage kommt, dass die neueren WR nicht (mehr) dieses Register unterstützen. Wie üblich wurde die Dokumentation nicht angepasst. (https://www.photovoltaikforum.com/thread/136374-sma-sunny-tripower-10-0-stp10-0-3av-40-tagesertrag-per-modbus-auslesen/?postID=1841356#post1841356) 
Es scheint somit zumindest den STP 8.0 und STP 10.0 zu betreffen.

Macht es hier Sinn auf das alternative Register 30529 "Gesamtertrag" zu wechseln? Das Register sollte ja sicher bei allen WR angegeben werden und in der gleichen Genauigkeit (Wh) vorliegen, oder?

**Comment by Maverick78de** [comment]
Ich nutze Register 30535 für den Tagesertrag. Dieser steht auch bei meinem neuen STP 6.0 und dem 8.0 (Firmware  3.10.11.R) zur Verfügung. Der Grund für einen Wechsel auf Register 30529 erschließt sich mir daher nicht.  30517 kommt in diesem Projekt nicht zum Einsatz.

**Comment by Maverick78de** [comment]
Auf aktuelle Firmware Updaten -> https://www.sma.de/service/downloads.html
